### ISSUE TITLE
LSI SAS Adapter not Found

### ISSUE THREAD

**Issue by miguemely** [Fohdeesha/lab-docu#11]
When trying to set the SAS Address, I see the following:
![image](https://user-images.githubusercontent.com/1568683/93719529-203cce00-fb51-11ea-9969-3596add8f957.png)

lspci | grep LSI shows the following:

![image](https://user-images.githubusercontent.com/1568683/93719531-2af76300-fb51-11ea-82f2-f7a2dce2c13a.png)

**Comment by miguemely** [comment]
I also saw this on boot: 
![image](https://user-images.githubusercontent.com/1568683/93720319-44e77480-fb56-11ea-84ce-8127f608f2cf.png)

**Comment by miguemely** [comment]
Got it working. Just did the restore and tried again.

**Comment by Fohdeesha** [comment]
Glad to hear - the dell firmware is really insidious and sometimes the first wipe does not get everything which results in issues like this - the solution is always a revert back to the latest stock firmware, and re-following the guide as you did.
