### ISSUE TITLE
Controller option not showing after Successful Flashing

### ISSUE THREAD

**Issue by sh4rkt3ch** [Fohdeesha/lab-docu#14]
Hi

I have a Dell R720 and i flashed my 710p mini D1 with the ability to boot from the BIOS and everything went without error but now i don't see the option to manage the card.

TrueNAS sees the HDDs and installs the OS to the HDDs but the server doesn't see the HDDs so just sits there saying no bootable devices.

Thanks in advance

**Comment by Fohdeesha** [comment]
Hi, I'm assuming you got this figured out?

**Comment by sh4rkt3ch** [comment]
Yeah sorry, flashed the uefi fw and had it in bios mode. Doh<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: Jon Sands ***@***.***> </div><div>Date: 13/05/2021  21:51  (GMT+00:00) </div><div>To: Fohdeesha/lab-docu ***@***.***> </div><div>Cc: sh4rkt3ch ***@***.***>, State change ***@***.***> </div><div>Subject: Re: [Fohdeesha/lab-docu] Controller option not showing after Successful Flashing (#14) </div><div>
</div>Hi, I'm assuming you got this figured out?
