### ISSUE TITLE
Didn't take note of SAS

### ISSUE THREAD

**Issue by icepicknz** [Fohdeesha/lab-docu#15]
Hi,

I read the introduction then clicked into H710P D1 and didn't take note that I needed to record the sas address.
What do I need to do now to set the sas address? can I just use your example, or how do I generate a new one?

Thanks
Barry

**Comment by Fohdeesha** [comment]
you can just use the example :) the only thing that matters is that it is not the same SAS address of another HBA in your system, which is not an issue as well when you only have one HBA installed
