### ISSUE TITLE
Fixing h310 mini with uart port?

### ISSUE THREAD

**Issue by Fapiko** [Fohdeesha/lab-docu#17]
Before I found this guide, I attempted cross-flashing my h310 mini in an R720 with the traditional guides, not realizing the motherboard would look for the Dell vendor code and halt booting. I'm hoping I can restore the Dell firmware via the UART port - won't have a chance to look at it for a while. Is this something you've done or looked into before?

Happy to document my findings when I get around to it if it's not something you've investigated.

**Comment by Fohdeesha** [comment]
Hi, the UART port doesn't provide any flash modification commands that would be usable to flash firmware back. If you're curious, I've attached the UART output/options from PERC Minis, you can see it's really only for debugging running firmware

Thankfully H310 Minis are only $15 on ebay, so you should be able to just pick up a replacement

[UART Commands.txt](https://github.com/Fohdeesha/lab-docu/files/6637818/UART.Commands.txt)

**Comment by Fapiko** [comment]
Yeah - I played around with it on Wednesday and actually couldn't get any UART data or response from it so I was assuming that it needed firmware running and likely wouldn't have a way to load firmware. Already have a replacement but the engineer in me still wants to fix this one :)

I did find https://www.ebay.com/itm/363426647832?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649 which Art of Server has a video of using to restore bricked perc minis, going to attempt that next.
