### ISSUE TITLE
It appears to be possible to check the PERC model in linux image instead

### ISSUE THREAD

**Issue by leeyc0** [Fohdeesha/lab-docu#18]
The freedos info.bat script checks the PERC model by executing megacli to check the model, which is perfectly possible to do it in linux instead. Putting info.bat in linux instead saves one reboot.

**Comment by Fohdeesha** [comment]
Indeed, we can check the model in Linux, but you would still have to boot the freedos iso to run the firmware erasure and SBR flashing scripts. We tried for some time to get these steps working under Linux to save a reboot, but the minis will not allow the firmware to be entirely wiped and a new sbr flashed, hence the freedos ISO

**Comment by leeyc0** [comment]
Oh you are correct. I only read H310 doc which the firmware was erased in Linux too, however it is not applicable to other cards.
