### ISSUE TITLE
Ruckus pulled firmware 08090m, which is used in guide

### ISSUE THREAD

**Issue by matthewbarreiro** [Fohdeesha/lab-docu#23]
As seen on the download page [here](https://support.ruckuswireless.com/software/3084-ruckus-icx-fastiron-08-0-90m-ga-software-release-zip):
> 2 September 2021:  RUCKUS has found a defect # FI-247944 due to which we have removed the software image for 08.0.90m from the Support Portal. For more information, please read [TSB-2021-005](https://support.ruckuswireless.com/articles/000011876) 

I can't actually see the details on that issue as I do not have a support contract, but a search shows this:

![image](https://user-images.githubusercontent.com/24529040/136709729-b0520c95-53c7-4b3c-a9ed-1fc7548cb16c.png)

Although the firmware is being used as an intermediate firmware to flash 08095d UFI, it may be worth changing the guide to use 08090k instead of 08090m. 

Thoughts?

**Comment by Fohdeesha** [comment]
Hi! thanks for the report. as the release says, the routing image is not affected, and that's what is in the guide. It was a bug with lost management access to the switch on the limited layer2 only firmware image which is not in use. And as you said, it's only used to jump to 8095. I'll probably update it to 8090n whenever that comes out
