### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jmott85** [Fohdeesha/lab-docu#25]
Hello,

It seems the link to the Dell doc on this line is broken.

https://github.com/Fohdeesha/lab-docu/blob/6656f3d0bf7da2f046fd0dd894f1219e00847df9/docs/perc.md?plain=1#L112

**Comment by Fohdeesha** [comment]
Hi! As this repo says in the description/readme, these markdown doc files are not intended to be used/displayed on GitHub, they are compiled using mkdocs and hosted on my website. All the URLs in these markdown sources are relative for portability, and they indeed work correctly once compiled using mkdocs and uploaded to my site. See the link here: https://fohdeesha.com/docs/perc.html#option-2-disable-thirdpartypcifanresponse-using-racadm-via-ssh

**Comment by jmott85** [comment]
Ahh makes sense.  Didn't catch that, thanks for clarifying.
