### ISSUE TITLE
M5015 flash to use IT MODE like H710 B0?

### ISSUE THREAD

**Issue by Phone-guy** [Fohdeesha/lab-docu#29]
I used your page and live iso files to successfully flash a H710 B0 card to 9205 8E in IT MODE and it worked fine. I am trying to flash an IBM M5015 which uses the same 2108 chip, but without success. After I do the dos iso and BIGB0CRS (which cleans and writes SBR successfully) to the M5015, then load the linux iso the next script does not do anything, it says 0 MPT found. 
Sas2Flash does not find the M5015 after writing to sbr either.  Is it possible to flash a M5015 with 2108 to it mode like your scripts did for the H710?
I have 2 M5015 and a AOC-SAS2P-H8IR also...both use the same LSI 2108 chip

**Comment by Fohdeesha** [comment]
The M5015 (LSI 9260) is not the same chip - the H710's are 2208 and 2308 chips, the 9260 based cards use the previous generation 2108 RoC chips (Raid-On-Chip) and these do not support IT mode flashing
