### ISSUE TITLE
Running sas-h310 returns no info

### ISSUE THREAD

**Issue by jjbrunton** [Fohdeesha/lab-docu#30]
Using an H310 on a standard desktop PC to flash it. When I boot into the linux disk I can see a Broadcom / LSI Megaraid in lsi but when running the sas-h310 I get no info.

**Comment by Fohdeesha** [comment]
what's the output of the following commands?

```
/opt/MegaRAID/MegaCli/MegaCli64 -AdpAllInfo -a0
```

```
lspci -nnv |grep -iA 18 lsi
```
