### ISSUE TITLE
Use a markdown linter

### ISSUE THREAD

**Issue by dngray** [Fohdeesha/lab-docu#32]
It might be worth checking out a markdown linter like [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) for visual studio, or [coc-markdownlint](https://github.com/fannheyward/coc-markdownlint) and [nvim-lint](https://github.com/mfussenegger/nvim-lint).

![3330334526](https://user-images.githubusercontent.com/48640805/162204228-58318121-85f1-48b8-bbda-7a461dd6f77a.png)

We use that over at [Privacy Guides](https://privacyguides.org). We also use [mkdocs-material](https://squidfunk.github.io/mkdocs-material/), so good choice there.

Another thing I'd possibly suggest is a writing style guide, and use more [admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/).

**Comment by Fohdeesha** [comment]
Thanks! I'll look into it, granted I'm trying to spend minimal time on this repo these days (getting close to exhausting all possible help/hints for these platforms)
