### ISSUE TITLE
Incorrect DHCP disable command

### ISSUE THREAD

**Issue by jorddenn** [Fohdeesha/lab-docu#33]
On this page https://fohdeesha.com/docs/icx6430.html the command is `ip dhcp-client disable` but I get
```
ICX6430-48 Switch(config)#ip dhcp-client disable
Invalid input -> disable
Type ? for a list
```

From [here](https://docs.ruckuswireless.com/fastiron/08.0.50/fastiron-08050-dhcpguide/GUID-976E3C5F-75D9-45E3-99FD-D931036DA99F.html#:~:text=Enter%20the%20no%20ip%20dhcp,to%20disable%20the%20DHCP%20client.&text=On%20a%20router%2C%20enter%20the%20interface%20configuration%20mode.&text=2%2F1%2F1-,Enter%20the%20no%20ip%20dhcp%2Dclient%20enable,to%20disable%20the%20DHCP%20client), the command is `no ip dhcp-client enable` which works for me. I can use `ip dhcp-client enable` after and it doesn't complain with
```
ICX6430-48 Switch(config)#ip dhcp-client enable
Error: Client already enabled
```

**Comment by Fohdeesha** [comment]
Well that's strange, I've tested locally on 6450 and 6610 and it's definitely `ip dhcp-client disable` - the documentation you linked is for fastiron 8050, which is much newer than the 8030 the icx6xxx series runs. Looking at the appropriate 8030 documentation (which is included in the firmware zip on my site) indicates what's going on however:

![image](https://user-images.githubusercontent.com/1357246/186536135-ef6aeeec-73ce-4a0f-a56e-c1a01d604f53.png)

The guide is correct for the layer3 image (which all the switches except for the 6430 runs), but for the layer2 only image the command is indeed different as you ran into. I'll update the icx6430 page

**Comment by Fohdeesha** [comment]
fix is live on the site, thanks for the report!

**Comment by jorddenn** [comment]
Yeah a quick google search brought me there, I saw that it was for the 8050 but it seemed to have worked so I wasn't going to speculate on something I know nothing about so I just pasted it in 😉 

Thanks boss
