### ISSUE TITLE
[Question] H710 D1 -IDRAC- RAC0501: There are no physical disks to be displayed. 

### ISSUE THREAD

**Issue by xkpx64** [Fohdeesha/lab-docu#35]
Hellow gentlemens , sorry if place is wrong but can i ask is it suppose to be that way in iDrac (to no show anything) ?
![Untitled](https://user-images.githubusercontent.com/5773378/210241484-00dddad8-b814-4b67-9cda-f4130eb2b0cd.png)
![as](https://user-images.githubusercontent.com/5773378/210247140-49f04b5f-aeae-4f4f-88b9-ca501c02d570.png)
![3](https://user-images.githubusercontent.com/5773378/210250581-0cb0842a-b3e9-4277-84a0-ae24ce502a43.png)
My steps was:
Firstly update bios and all stuf possible via Dell EMC
Second read the guide as follows:
- Disable few options (VT, SR-IOV, I/OAT)  in bios and set to BIOS - not UEFI
- Remove battery from controller 
- D1CROSS + reboot - 
- sudo su -,  D1-H710 , reboot , SAS Address Back
- Enable the few options back

**Comment by Fohdeesha** [comment]
this is expected - idrac relies on dell perc firmware to read info about the raid controller and attached disks. Because you've cross flashed to pure LSI IT firmware, that's not going to happen anymore, idrac will be totally unaware of it.
