### ISSUE TITLE
PERC H710 - No LSI SAS Adapter not Found!

### ISSUE THREAD

**Issue by Pegoku** [Fohdeesha/lab-docu#42]
i'm trying to flash a H710 to LSI

Card: ![](https://github.com/Fohdeesha/lab-docu/assets/81113533/5b523e0f-a4de-4226-979b-b71e4ed90f00)

The card is connected ![](https://github.com/Fohdeesha/lab-docu/assets/81113533/2c09e182-ea79-4752-a3d1-11c9ee09f4fb)
But not detected ![](https://github.com/Fohdeesha/lab-docu/assets/81113533/f947e7a4-d627-4886-8e28-efea3de73ecc)
![](https://github.com/Fohdeesha/lab-docu/assets/81113533/0aba30f0-d4ec-46d2-9caf-8d2398c465ea)

Can't revert because the program can't detect the card

**Comment by Pegoku** [comment]
Changed the card's PCIe port, it seems to be detected by DOS

**Comment by Fohdeesha** [comment]
Did you already run the "D1-H710" crossflash command in linux?, and before that, the "BIGD1CRS" command in dos? If so, the dos ISO won't detect it anymore, its info command only looks for stock dell cards. You can still run `BIGD1RVT` in the dos ISO to fully flash back to dell, do a cold power off, power back on and try again

**Comment by Pegoku** [comment]
Sorry for late response, I forgot to write it.
It was solved by changing the PCIe slot.

**Comment by Bryvo01** [comment]
I had this problem and it was b/c I also had a PERC 6/E; pulled the external card and e'ery thing went great.

**Comment by Fohdeesha** [comment]
@Bryvo01 that's why the guide says at the very beginning to ensure you only have one raid adapter in the system before continuing :)
