### ISSUE TITLE
I made a Chinese Translated version

### ISSUE THREAD

**Issue by liups233** [Fohdeesha/lab-docu#43]
[PERC 阵列卡刷入直通固件.pdf](https://github.com/Fohdeesha/lab-docu/files/15038925/PERC.pdf)
[PERC 阵列卡刷入直通固件.docx](https://github.com/Fohdeesha/lab-docu/files/15038926/PERC.docx)

Recently, more people in China have begun to use these old PERC cards, so I made a translated version. 

Can I send the translated files to those needed ( because your tutorial is under GPL 3 License)

Thanks

**Comment by Fohdeesha** [comment]
Sure! Thank you for the translations. Feel feel to distribute however you see fit, as long as the credits stay in there. I think GPL 3 was the default license when creating this repo, I'm not very worried about strictly adhering to it

**Comment by liups233** [comment]
Got it. Thank you
