### ISSUE TITLE
Ventoy - Memdisk - "No ramdisk image specified!" (FreeDOS)

### ISSUE THREAD

**Issue by BloodyIron** [Fohdeesha/lab-docu#45]
Hey so first, thanks a tonne for all those involved in this documentation and the tooling! Huge props.

Second, I'm trying to use Ventoy to boot into FreeDOS to do an H710 Mini IT Cross-flashing.

The doc page here: https://fohdeesha.com/docs/perc.html

Mentions that I need to boot the FreeDOS ISO in Memdisk mode, and I've tried that a few different ways. I also made sure to go disable those settings in the BIOS the same page outlines, switch to BIOS (from EFI) mode. Pretty sure I did all the steps I need to (maybe I missed something?).

Anyways each attempt to boot into the FreeDOS ISO from Ventoy via MEMDISK mode results in "MEMDISK: No ramdisk image specified!", screenshot (I love iDRAC hehe):

![image](https://github.com/user-attachments/assets/9249b935-9fd8-4969-9520-2880be9c8a6b)

Unsure if this is a bug or if the issue is PEBKAC. Can anyone point me in the right direction please?

Thanks again for all this stuff! Important for keeping perfectly good servers out of the landfill :)

**Comment by Fohdeesha** [comment]
Hi, this is a bug/issue in ventoy, this would be better opened against their repo. I ran into the same issue when originally creating the guide, the initial plan was to provide a single ventoy ISO that could boot either linux or dos, but ventoy has a ton of weird little bugs whe nit comes to booting older DOS images

**Comment by BloodyIron** [comment]
> Hi, this is a bug/issue in ventoy, this would be better opened against their repo. I ran into the same issue when originally creating the guide, the initial plan was to provide a single ventoy ISO that could boot either linux or dos, but ventoy has a ton of weird little bugs when it comes to booting older DOS images. to work around this, just boot the ISO directly as the guide instructs
> 
> edit: I see now what you mean about the guide mentioning ventoy, I don't recall adding that - I think someone submitted a PR with that addition and I accepted it without personally testing. will probably remove that line

Well I think the first time I tried booting it without memdisk (but that could be a faulty memory).

So am I understanding correctly that your recommendation is to try booting from the FreeDOS ISO _without_ memdisk mode? Or did you mean to convey something else?

Also, thanks a tonne for your work on all this! :D

**Comment by Fohdeesha** [comment]
my recommendation is to not use ventoy at all, and just boot the freedos ISO directly, either with idrac virtual media, or burn it to a usb drive using rufus or similar. As I said I could never get ventoy to work with a few dos bootloaders no matter what I did
