### ISSUE TITLE
Will my old config be kept?

### ISSUE THREAD

**Issue by theskipster** [Fohdeesha/lab-docu#7]
Hi.  Thanks for posting the instructions for flashing "IT Mode" for the 710P Mini. I do have one question, though.

I want to reflash my 710P Mini with the LSI firmware here: https://github.com/Fohdeesha/lab-docu/blob/master/docs/H710P-B0.md (not sure if I have a B0 or a D1 at the moment)

Will I be able to preserve my current RAID config and data, or will this reinitialize the whole RAID array and I will need to restore from backup?

More details about my specific setup can be found here:  https://www.reddit.com/r/homelab/comments/gk8a46/migrate_perc_710p_mini_to_sas_92078i/

Any insight you can offer before I jeopardize 10+ TB of data would be awesome.

**Comment by Fohdeesha** [comment]
I have no idea, that's totally dependent on the software raid that unraid uses. It will go from seeing your disks as megaraid virtual disks to seeing them as actual disks (whatever model they may be). If it's a smart file system like ZFS that stores a UUID and array identifier on the disk, it will automatically pull that info off them and the array will come right back up unchanged. No idea what unraid uses though. If it's anything sane and from this century I would wager the array would come right back up, or worst case you would have to do a manual import

**Comment by theskipster** [comment]
OK, thanks.  It might just be worth the try at this point in time.  I will give it a try sometime next week and let you know how it goes.
